/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface RandomProofOptimizedInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getRandomnessForEntityHash"
      | "getRequestDetails"
      | "getRequestIdForEntityHash"
      | "isEntityHashProcessed"
      | "rawFulfillRandomWords"
      | "requestRandomness"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "RandomnessFulfilled" | "RandomnessRequested"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getRandomnessForEntityHash",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getRequestDetails",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRequestIdForEntityHash",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isEntityHashProcessed",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "rawFulfillRandomWords",
    values: [BigNumberish, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "requestRandomness",
    values: [string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getRandomnessForEntityHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRequestDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRequestIdForEntityHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isEntityHashProcessed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rawFulfillRandomWords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestRandomness",
    data: BytesLike
  ): Result;
}

export namespace RandomnessFulfilledEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    entityHashBytes32: BytesLike,
    randomness: BigNumberish
  ];
  export type OutputTuple = [
    requestId: bigint,
    entityHashBytes32: string,
    randomness: bigint
  ];
  export interface OutputObject {
    requestId: bigint;
    entityHashBytes32: string;
    randomness: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RandomnessRequestedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    entityHashBytes32: BytesLike,
    entityHash: string,
    salt: string,
    requester: AddressLike
  ];
  export type OutputTuple = [
    requestId: bigint,
    entityHashBytes32: string,
    entityHash: string,
    salt: string,
    requester: string
  ];
  export interface OutputObject {
    requestId: bigint;
    entityHashBytes32: string;
    entityHash: string;
    salt: string;
    requester: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RandomProofOptimized extends BaseContract {
  connect(runner?: ContractRunner | null): RandomProofOptimized;
  waitForDeployment(): Promise<this>;

  interface: RandomProofOptimizedInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getRandomnessForEntityHash: TypedContractMethod<
    [entityHash: string],
    [[bigint, boolean] & { randomness: bigint; fulfilled: boolean }],
    "view"
  >;

  getRequestDetails: TypedContractMethod<
    [requestId: BigNumberish],
    [
      [string, string, bigint, string, bigint, bigint, boolean] & {
        entityHashBytes32: string;
        saltHash: string;
        randomness: bigint;
        requester: string;
        requestBlock: bigint;
        fulfilledBlock: bigint;
        fulfilled: boolean;
      }
    ],
    "view"
  >;

  getRequestIdForEntityHash: TypedContractMethod<
    [entityHash: string],
    [bigint],
    "view"
  >;

  isEntityHashProcessed: TypedContractMethod<
    [entityHash: string],
    [boolean],
    "view"
  >;

  rawFulfillRandomWords: TypedContractMethod<
    [requestId: BigNumberish, randomWords: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  requestRandomness: TypedContractMethod<
    [entityHash: string, salt: string],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getRandomnessForEntityHash"
  ): TypedContractMethod<
    [entityHash: string],
    [[bigint, boolean] & { randomness: bigint; fulfilled: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRequestDetails"
  ): TypedContractMethod<
    [requestId: BigNumberish],
    [
      [string, string, bigint, string, bigint, bigint, boolean] & {
        entityHashBytes32: string;
        saltHash: string;
        randomness: bigint;
        requester: string;
        requestBlock: bigint;
        fulfilledBlock: bigint;
        fulfilled: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRequestIdForEntityHash"
  ): TypedContractMethod<[entityHash: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "isEntityHashProcessed"
  ): TypedContractMethod<[entityHash: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "rawFulfillRandomWords"
  ): TypedContractMethod<
    [requestId: BigNumberish, randomWords: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestRandomness"
  ): TypedContractMethod<
    [entityHash: string, salt: string],
    [bigint],
    "nonpayable"
  >;

  getEvent(
    key: "RandomnessFulfilled"
  ): TypedContractEvent<
    RandomnessFulfilledEvent.InputTuple,
    RandomnessFulfilledEvent.OutputTuple,
    RandomnessFulfilledEvent.OutputObject
  >;
  getEvent(
    key: "RandomnessRequested"
  ): TypedContractEvent<
    RandomnessRequestedEvent.InputTuple,
    RandomnessRequestedEvent.OutputTuple,
    RandomnessRequestedEvent.OutputObject
  >;

  filters: {
    "RandomnessFulfilled(uint256,bytes32,uint256)": TypedContractEvent<
      RandomnessFulfilledEvent.InputTuple,
      RandomnessFulfilledEvent.OutputTuple,
      RandomnessFulfilledEvent.OutputObject
    >;
    RandomnessFulfilled: TypedContractEvent<
      RandomnessFulfilledEvent.InputTuple,
      RandomnessFulfilledEvent.OutputTuple,
      RandomnessFulfilledEvent.OutputObject
    >;

    "RandomnessRequested(uint256,bytes32,string,string,address)": TypedContractEvent<
      RandomnessRequestedEvent.InputTuple,
      RandomnessRequestedEvent.OutputTuple,
      RandomnessRequestedEvent.OutputObject
    >;
    RandomnessRequested: TypedContractEvent<
      RandomnessRequestedEvent.InputTuple,
      RandomnessRequestedEvent.OutputTuple,
      RandomnessRequestedEvent.OutputObject
    >;
  };
}
