/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRandomProof,
  IRandomProofInterface,
} from "../../../../src/mocks/MaliciousReentrant.sol/IRandomProof";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "entityHash",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "salt",
        type: "bytes32",
      },
    ],
    name: "requestRandomness",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IRandomProof__factory {
  static readonly abi = _abi;
  static createInterface(): IRandomProofInterface {
    return new Interface(_abi) as IRandomProofInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IRandomProof {
    return new Contract(address, _abi, runner) as unknown as IRandomProof;
  }
}
